### ISSUE TITLE
Show command doesn't do anything

### ISSUE THREAD

**Issue by ghost** [rwirdemann/obsidian-week-planner#1]
Hi!
I have installed this plugin and read that the show commands should generate the relevant documents but it does nothing and I have no idea how to get the logs to see what's happening.

**Comment by rwirdemann** [comment]
Hi,

tested it on Mac OS only. Are you on a different operating system? Could you open the "Developer Tools" under "View" and send me the error log?

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/92577100/196643036-85cad9da-b15a-4e4d-9519-44c0e3075e0c.png)
I'm on Windows. Apparently it does not create the files so it can't open them.

**Comment by rwirdemann** [comment]
Does the log contain an error above the ones you've sent? I'm looking for the error message that is raised when the files or directories are created.

Does your file system support blanks in subdirectories?

Was the directory "Week Planner" or "Days" created?

**Comment by ghost** [comment]
No other logs in the console.   I created the folders manually and now it works.
Maybe update the docs to create the folder structure manually or I'm doing something wrong?

**Comment by rwirdemann** [comment]
Thanks for the hint. The plugin should create the directories on windows automatically. I will get access to a windows machine and fix it.

**Comment by rwirdemann** [comment]
Fixed in 0.0.2
