### ISSUE TITLE
Allow Working Weekends

### ISSUE THREAD

**Issue by gypsyav** [rwirdemann/obsidian-week-planner#5]
This is a great plugin but it's hard to use for those of us who don't work a traditional Mon-Fri work week. In order to schedule any tasks on a Sat or Sun right now it has to be cut and pasted it would be nice to be able to use the keyboard shortcuts to move something from Fri, Sat, or Sun's note to the next day or from the inbox to Sat or Sun. 

I thought this was possible by adding Sat and Sun to the work week in options as per the example but it doesn't work. Even with Sat and Sun added to the work week hitting Alt-M on Fri or Sat moves the task to Mon and hitting on Sun does nothing at all on the daily pages and moves everything to Mon if in the inbox.

**Comment by rwirdemann** [comment]
Thanks for the report. Will add it to my list and fix it soon.

**Comment by rwirdemann** [comment]
fixed in 0.1.3
